### ISSUE TITLE
HDM: describe how parameters obtain their values when they are omitted

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-spec#11]
The semantics of optional parameters like `start_time`, `end_time`, `initial_size`, `final_size` must be precisely described in the documentation. It might be useful to start with an example of a "complete" demography, where nothing is omitted, and then discuss how the model remains unambiguous when removing one or more parameters.

**Comment by grahamgower** [comment]
Lots of stuff has now gone into the spec docs on this: https://popsim-consortium.github.io/demes-spec-docs/main/spec.html. The major bit which is outstanding is the `epochs` section, and how times and sizes propagate to adjacent epochs when not specified. Not hard, just not yet done.

**Comment by jeromekelleher** [comment]
Docs look great BTW!

**Comment by grahamgower** [comment]
I think this is covered by the separation of the spec into MDM and HDM. And this issue essentially says "The HDM needs completing".

**Comment by grahamgower** [comment]
The HDM resolution section is now complete.
