### ISSUE TITLE
specify the encoding is UTF8

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-spec#129]
JSON and YAML suport other encodings (at least utf-16 and utf-32). I'm not sure if we can be agnostic here, or not? In any event, Python on Windows doesn't default to a sane encoding, so we can expect unicode-related annoyances there.

**Comment by molpopgen** [comment]
I think this is the way to go. 

What does Python do on Windows, btw?

**Comment by grahamgower** [comment]
I'm thoroughly confused about Windows, and localisation in general. But see
https://docs.python.org/3/using/windows.html#utf-8-mode
and
https://vstinner.github.io/python37-new-utf8-mode.html

**Comment by jeromekelleher** [comment]
I would just stay away from this minefield - I don't see what problem we're fixing by having an opinion about it. It's up to implementations at the end of the day what text encodings they support.

**Comment by grahamgower** [comment]
The problem (I think) is that one cannot, in general, determine the encoding of a given file automatically. So we must say "let's interpret this file as utf-8" (or some other encoding) when it is opened/read. Some non-ascii bytes are valid in multiple encodings, but have different interpretations in those distinct encodings. On MacOS and Linux, files are read as utf-8 by default. On Windows, it seems that by default this is dictated by the current locale setting.

I think this means that someone could write a yaml file on Linux or MacOS using a unicode name, and the file would then be decoded on Windows using a mystery encoding where the non-ascii bytes are potentially not even valid (and thus the file would be unreadable).

On the other hand, if we say all yaml and json files must be utf-8, then any parser that exhibits this problem on Windows is simply non-conformant. Not only that, there is a simple fix (explicitly open the file as utf-8).

**Comment by jeromekelleher** [comment]
I don't think we can do much about the text encoding that people use, and even if we did go to the trouble of specifying an encoding it wouldn't do any good.  Let's not worry about it.

**Comment by jeromekelleher** [comment]
Sorry, I think I misunderstood here - if it's just specify an encoding in our *code* so that the tests pass, then totally, let's do that.

I thought you meant, "let's talk about text encodings in the specification and require that people use utf8".

**Comment by grahamgower** [comment]
Hmm, well we have to do the latter if we do the former. In demes-python we want to test against the spec test cases, which include files with unicode in deme names. To make the tests pass (https://github.com/popsim-consortium/demes-python/pull/430) we thus need to open the files with `encoding="utf8"` --- not just in the tests themselves, but in the code path that users use to load files into demes-python. Subsequently, this means that users will have to write their yaml files with utf8 as their encoding, because their yaml files won't be loaded correctly otherwise.

Yeah, its a pain. The alternative, I guess, is to leave this all alone (skip tests on Windows), and then we have Windows users writing yaml files with mystery encodings that no one else can read (possibly not even Windows users with other locales) without reverse engineering the encoding or renaming the deme names.

**Comment by jeromekelleher** [comment]
I mean we can write it into the spec if we like, I just don't think it'll make any difference to whether people encounter the problems in practise. Text encoding is a problem beyond our control.

**Comment by grahamgower** [comment]
I think you're right @jeromekelleher. Let's open files as utf-8, but avoid saying anything about the encoding in the spec. Whatever we do, something will break for someone, so lets wait for someone to complain.
