### ISSUE TITLE
rename parser.py to avoid conflict with possibly built-in stdlib module

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-spec#131]
On some Python installations (specifically Windows for Python<=3.9), the stdlib [parser](https://docs.python.org/3.7/library/parser.html) module is included as a built-in module. This means the search path when doing `import parser` will import the built-in module instead of a file named parser.py in the search path. The import itself succeeds, so this exhibits itself as an AttributeError when attempting to call `parser.parse()`. E.g. running `reference_implementation/resolve_yaml.py`.

https://github.com/popsim-consortium/demes-spec/runs/6159151437?check_suite_focus=true

Note that the parser stdlib module is deprecated and was removed in Python 3.10.

Do we care? Should we rename parser.py?

**Comment by jeromekelleher** [comment]
Aha.

Simplest to rename it to ``demes_parser.py`` or something?
