### ISSUE TITLE
tag a 1.0 beta

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-spec#136]
for the biorxiv manuscript

**Comment by jeromekelleher** [comment]
Did we do this?

**Comment by jeromekelleher** [comment]
Might as well tag now I think, we're not making any more substantive changes.

**Comment by grahamgower** [comment]
I have some train/plane time tomorrow and was planning to do another pass through specification.md.

**Comment by jeromekelleher** [comment]
OK, sounds good. Whenever you think it's ready.
