### ISSUE TITLE
Migration resolution missing a "MUST error" statement

### ISSUE THREAD

**Issue by molpopgen** [popsim-consortium/demes-spec#147]
In the section on resolving migration start/end times, there's no mention of what to do if the demes do not co-exist.  This is a "MUST error" case, I believe?

**Comment by grahamgower** [comment]
This is one of the things that might belong under the "validation" section (which is currently missing). There are other items which are mixed in the resolution section and MDM section that might better fit under validation. Patches welcome!

**Comment by molpopgen** [comment]
I'll see how I implement it the validation step.  That'll give me an idea of what to write.

**Comment by grahamgower** [comment]
Great! Any suggestions you have on how to organise the information is welcome too.

**Comment by molpopgen** [comment]
closed via #148
