### ISSUE TITLE
Pulse proportions

### ISSUE THREAD

**Issue by molpopgen** [popsim-consortium/demes-spec#149]
The spec currently states that the sum of proportions must be <= ~1.  Shouldn't they also be > ~0.0 as well?

**Comment by grahamgower** [comment]
I think that's implied by the valid range of values given in the schema.

**Comment by molpopgen** [comment]
D'oh -- I misread it, missing the "less than" bit.

**Comment by molpopgen** [comment]
Actually, I think I closed this mistakenly.  The spec says, "must sum to less than or equal to 1-ish", but my question is that it does not say  that the sum must not be zero:

```
 The proportions must sum to less than or equal to 1 (within a reasonable tolerance, e.g. 1e-9).
```

**Comment by grahamgower** [comment]
But this is implied by the schema---each value must be > 0, so their sum must be > 0.
https://github.com/popsim-consortium/demes-spec/blob/5cccce07d725a799498a6c53f489fbad4a59ecdf/schema/mdm-v1.0.yaml#L59-L62

So the validation section should say something about validation of the schema (required properties, value ranges, etc).

**Comment by molpopgen** [comment]
> But this is implied by the schema---each value must be > 0, so their sum must be > 0.
> 
> https://github.com/popsim-consortium/demes-spec/blob/5cccce07d725a799498a6c53f489fbad4a59ecdf/schema/mdm-v1.0.yaml#L59-L62
> 
> So the validation section should say something about validation of the schema (required properties, value ranges, etc).

Yes, I'm just not sure that's the section that people will read if they can avoid it :).

I'll do a PR next week on a validation section for pulses.

**Comment by grahamgower** [comment]
I add a bunch of stuff under the validation section of the spec. Reopen if you thing anything is unclear or missing.
