### ISSUE TITLE
Add "how to cite" section to the docs

### ISSUE THREAD

**Issue by xin-huang** [popsim-consortium/demes-spec#153]
Hi @grahamgower 

I am revising a manuscript and making plots with `demes` and `demesdraw`.
How to cite `demes` and `demesdraw`?

**Comment by apragsdale** [comment]
Hi @xin-huang - it's great to hear that Demes (and demesdraw) is getting use! Graham might have another idea for demesdraw specifically, but the Demes preprint is now posted and cite-able! doi: https://doi.org/10.1101/2022.05.31.494112

**Comment by grahamgower** [comment]
Hey @xin-huang. As @apragsdale says, the preprint is the thing to cite.

**Comment by xin-huang** [comment]
Hi @grahamgower, since `demesdraw` is not cite-able yet, I would like to thank you in the acknowledgment section. Is that ok?

**Comment by grahamgower** [comment]
Yes, that's certainly fine with me. Thanks. :)
