### ISSUE TITLE
Building docs on Python 3.10

### ISSUE THREAD

**Issue by molpopgen** [popsim-consortium/demes-spec#157]
A venv seeded w/the contents of requirements.txt gives this error when running docs/Makefile:

ImportError: cannot import name 'Union' from 'types' (/usr/lib/python3.10/types.py)
make: *** [Makefile:2: all] Error 1

**Comment by grahamgower** [comment]
Uggghhh... sphinx 3.5.x is broken on Python 3.1.0. Looks like we'll need to update sphinx, which means we need to update jupyter-book, which breaks the "panel" feature we're using for the tabs in the tutorial.

**Comment by grahamgower** [comment]
Ooh, `pip install sphinx==4.5.0` works. But I'll need to fix the panel stuff sometime anyhow.

**Comment by jeromekelleher** [comment]
Yuck

**Comment by grahamgower** [comment]
Jupyer-book deprecated the extension they were using for panels. There's a replacement though. I don't know if its a 1 minute job or a 1 hour job to change over.
https://jupyterbook.org/en/stable/reference/_changelog.html#v0-13-0-2022-06-02

**Comment by molpopgen** [comment]
Maybe I need to take a look at my docs under 3.10 and see what they actually look like...
