### ISSUE TITLE
initial_size<1 or final_size<1 should be an error

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-spec#17]
We currently enforce that Ne>0, but it should be Ne>=1. Unless there is some circumstance under which `0 < Ne < 1` makes sense?

**Comment by jeromekelleher** [comment]
What about people things like working in coalescent units? Fractional Ne values < 1 might make sense then? I don't think there's much to be gained from putting an upper limit on it.

**Comment by grahamgower** [comment]
Happy to leave it as it is, I just noticed that hypothesis was often (mostly?) generating graphs that won't be useful. Eg. parameters at the edge of their range, like `~1e±308`.

**Comment by jeromekelleher** [comment]
That's fine I think. No point in being too prescriptive unless we're preventing errors that we *know* will happen (rather than preventing stuff we think probably doesn't make sense)

**Comment by grahamgower** [comment]
Ok, closing. :)
