### ISSUE TITLE
build/render docs and find them a home

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-spec#2]
In #1, I created `sphinx` docs. We aren't building these using CI yet. We should. But this opens the question of where the docs should live. `demes-python` is currently building sphinx docs in a CI action and pushing the built docs to the https://github.com/popsim-consortium/demes-docs repository, which is then hosted via github pages at https://popsim-consortium.github.io/demes-docs/main/index.html. So we could make a new `demes-spec-docs` repository, and do the same thing.  Or we could push the demes-spec docs to the same demes-docs repository, e.g. in its own subdirectory.

Or we could choose to avoid sphinx for the spec docs, and do something else? Github pages supports rendering markdown natively, which is probably the simplest thing we could do. But automatically building docs from the spec.yaml file wouldn't work (or would be a custom job).

**Comment by jeromekelleher** [comment]
Sphinx seems like a good option overall, even if just for the ability to link things together and render code chunks. It's probably simplest to create the ``demes-spec-docs`` repo and serve from GitHub pages? I don't have strong opinions about this, whatever ends up being the simplest.

It might be worth waiting until we have a fairly finished version of the docs before we consider this question again, though.

**Comment by grahamgower** [comment]
Ok, I'll copy across the docs CI from the demes-python repo, and upload into `demes-spec-docs`.

**Comment by grahamgower** [comment]
Looks like we're now up and running!
