### ISSUE TITLE
disallow pulse migrations at time=0?

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-spec#22]
I think this defines an event where the outcome can't be observed, so we should explicitly disallow it. We already don't allow a deme to have start_time=0.

**Comment by grahamgower** [comment]
More generally, we should disallow pulses into a deme at the deme's `end_time`. I'm not 100% sure about pulses *from* a deme at the deme's `end_time`, but I think that should be allowed.

**Comment by jeromekelleher** [comment]
SGTM, corresponds to the open-closed time interval, right?

**Comment by grahamgower** [comment]
> SGTM, corresponds to the open-closed time interval, right?

Yeah, exactly. Maybe we should enumerate the possibilities here for concreteness... Suppose we construct the graph:
```python
b = Builder(defaults=dict(epoch=dict(start_size=100)))
# deme A exists on the interval (start_time=inf, end_time=0]
b.add_deme("A") 
# deme B exists on the interval (start_time=100, end_time=50]
b.add_deme("B", start_time=100, epochs=[dict(end_time=50)])
g = b.resolve()
```
Then the following should be valid:
```python
b.add_pulse(source="A", dest="B", time=g["B"].start_time)
b.add_pulse(source="B", dest="A", time=g["B"].end_time)
```

And the following invalid:
```python
b.add_pulse(source="A", dest="B", time=g["B"].end_time)
b.add_pulse(source="B", dest="A", time=g["B"].start_time)
```

**Comment by grahamgower** [comment]
The open-closed intervals are well described in the spec now, and both MDM and HDM disallow pulses at time=0.
