### ISSUE TITLE
Model resolution

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#24]
Here's an initial pass at writing down the resolution order for values in the graph, so that we go from a simplified graph to a full-qualified one (we should consider the inverse operation separately).

- Values that are specified in the ``defaults`` section of the JSON document are propagated downwards through the document tree and set in a preorder traversal.
- To resolve times and population sizes within demes, we start at the roots and visit demes in preorder (so, all ancestors will be fully qualified when we visit a particular deme). Within a deme, the times of each epoch are determined uniquely by the information supplied and the time information of parent demes. Population sizes are uniquely determined by the information within a deme.
- Migrations are then resolved.

How does this sound?

**Comment by grahamgower** [comment]
If a deme has only one epoch, it's permissible to specify the start/end time and initial/final size directly on the deme. So epochs might not exist until the demes are resolved. This means that the defaults will need to be pushed down to the demes level, and then as/after the deme's epochs are constructed, the deme default can be pushed into the epoch level. Not sure if this detail matters for what you're writing though.

**Comment by jeromekelleher** [comment]
> If a deme has only one epoch, it's permissible to specify the start/end time and initial/final size directly on the deme. 

Is there a previous discussion on times as properties of demes vs always requiring the existence of at least one epoch?

**Comment by grahamgower** [comment]
Possibly not since we first started discussing the yaml format in the old msprime issue.

**Comment by jeromekelleher** [comment]
I'll open an issue - it's not *totally* obvious it's worth the complexity.

**Comment by grahamgower** [comment]
Oh, #133. Feel free to reopen there.

**Comment by jeromekelleher** [comment]
Closing this as the semantics have been decided.
