### ISSUE TITLE
add set of test json files

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-spec#27]
> There's a question about how much CI etc we do with this. My vote would be to keep it fairly minimal.

I think it will be useful for the demes-spec repository to include a set of test yaml (or json) files. There would be two sets, one for valid input, and one invalid input. The intention is for these to be available for the development/testing of new implementations. The reference implementation could then be tested against these files in CI.

_Originally posted by @grahamgower in https://github.com/popsim-consortium/demes-spec/issues/26#issuecomment-739147092_

**Comment by jeromekelleher** [comment]
Good call.

**Comment by jeromekelleher** [comment]
Partially addressed in #26 and #40, but we should (a) expand and organise the examples better and (b) add some examples that fail.
