### ISSUE TITLE
Allow extra fields in the specification?

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#28]
An important question we should settle is whether we allow extra information to be included in the JSON/yaml object. That is, if there's an extra key at any level in the graph description, should parsers ignore this or should they throw an error? If we advise parsers to ignore extra data, then this gives a natural way for people to "extend" the specification by adding in more stuff to a demography model that only their simulator/inference method understands. This may be a good thing under the "be lenient in what you receive and strict on what you send" principle.

However, it may also be quite a bad thing in that it encourages fragmentation and random extensions in various directions that may or may not be appropriate. Another bad outcome is that it reduces our ability to effectively version the schema. Suppose msprime version x supports Demes version 1.0, and then Demes version 1.1 comes out which includes some extra information which msprime simulates. Then, msprime version x will happily accept the Demes version 1.1 model and silently produce a different simulation to what it would if had had a Demes 1.1 parser. This is surely a bad thing from a reproducibility perspective.

So, on balance, I think we should require that parsers raise an error if they see any information in the JSON payload that they don't recognise. 

Related to #20

Thoughts?

**Comment by grahamgower** [comment]
That's tough. I can see good arguments both ways. Disallowing extra information is going to end up being very restrictive. Lets say we want to output JSON objects as the posterior of an ABC/MCMC, but we're also optimising a parameter that's not part of the demographic model per se. E.g. recombination rate. The easiest way to output this jointly with the demographic model parameters, is to create a new toplevel namespace (e.g. prefixed with an `_underscore`) and just throw the additional parameter(s) there.

**Comment by jeromekelleher** [comment]
I agree, it is very restrictive. We could formalise the idea of having some place to put stuff that's not part of the spec?

From a software perspective, how would you imagine the demes-python parser return this information to the user? You don't really want to tack on arbitrary extra attributes to the Demes, Epoch etc classes at runtime, I expect.

**Comment by grahamgower** [comment]
Actually, maybe that use case is still ok. With the API we already have one would just `demes.load_asdict()` the file manually, filter the relevant info, then pass the result into `demes.Graph.fromdict()`. So maybe being restrictive is the right approach here.
