### ISSUE TITLE
Make single Migration class?

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#29]
I know we've been over this a few times, but I wanted to get a final discussion here for the record. From a parser implementation and specification perspective it would be a lot simpler if we just have a single class of migration. There are very good reasons for wanting both types, so I wonder if we could work around the issue as follows:

Migrations all have a start_time, end_time and a rate (blah blah blah). Migrations are either symmetric or asymmetric. In the asymmetric case, the ``source`` and ``dest`` demes must be specified. In the symmetric case the list of ``demes`` is specified. Either one of ``source`` and ``dest`` OR ``demes`` must be specified, but not both.

This seems to give us the behaviour we want, while simplifying the spec a bit, doesn't it?

**Comment by grahamgower** [comment]
That seems reasonable to me. If you don't think users will make more errors, then we could absolutely change it.

**Comment by jeromekelleher** [comment]
I don't think so - have either ``source`` and ``dest`` OR ``demes`` seems like a clear distinction between the two types. @apragsdale, what do you think?

**Comment by apragsdale** [comment]
I think that makes sense. It would simplify the code and spec a bit, and I don't see users making many errors with it. As with setting default rates, there is the danger of a lot of the behavior be implied, and thus less easily readable, but I think this one is fine.

**Comment by jeromekelleher** [comment]
@molpopgen - thoughts/objections?

**Comment by molpopgen** [comment]
No objection.  Sounds good to keep is as simple as possible.
