### ISSUE TITLE
Rename to start_size/end_size?

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#30]
It would perhaps be slightly easier to grok the connection between times and sizes if they shared the same prefix - i.e, ``start_size`` is the population size at ``start_time`` and ``end_size`` is the size at ``end_time``. Are "initial" and "final" just synonyms for "start" and "end" here,  without really adding any insight?

I'd imagine we went through this before... apologies for raking up stuff that's been settled already!

**Comment by grahamgower** [comment]
Yeah I think there was some discussion previously, but no consensus. So I closed the issue at some later point to ensure we could move forward. We can change it if you think it's worth it.

**Comment by jeromekelleher** [comment]
It's probably a minor but worthwhile change IMO. But, I don't feel strongly about it - @apragsdale, @molpopgen, votes?

**Comment by molpopgen** [comment]
Seems like a sensible change to me.

**Comment by apragsdale** [comment]
I have no problem with that
