### ISSUE TITLE
Rules about Epoch start/end times are unclear

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#32]
The current rules around how a Deme/Epoch's start_time is obtained are fairly clear currently, but it's not obvious to me what we're supposed to do with ``end_time``. Are we assuming that ``end_time`` should always be specified for an Epoch, and it's only start_time that can be omitted?

It's not obvious why we would allow for start_time values to be filled in, but not end_time values, since they're equally redundant in either direction. Suppose we have the intervals 
```
[(a, b), (b, c), (c, d)]
```
Then in principle we have stuff like the following without amibiguity (where X is "null")
```
[(a, X), (b, X), (c, d)]
[(a, b), (X, X), (c, d)]
[(a, X), (b, X), (c, d)]
[(a, X), (b, c), (X, d)]
```

Should we allow any mixture of missing values? If so, how do spell out what the rules are? I'm generally finding it a bit icky trying to nail down what the semantics are here on how time "flows" though the epochs and graph nodes.  I'm not a huge fan of the redundancy, but I'm not really seeing a better way to do it. The only thing that occurs to me is to store just the list ``times=[a, b, c, d]`` as an attribute of Deme, but that has a whole bunch of its own issues.

**Comment by grahamgower** [comment]
Yeah, this has ended up being a bit awkward. I think at different times we've had `demes-python` accept either missing start_times or missing end_times (or both?). The idea being that we could propagate values starting from the oldest time, or alternately starting from the youngest time. Probably we would encourage users to specify times as either `[(a, X), (b, X), (c, X)]` or `[(X, b), (X, c), (X, d)]`. There was some discussion of this in #10. But your examples certainly suggest there are other possibilities.

But isn't the rule just that we need each time in `times=[a, b, c, d]` to be defined (at least) once?  Concretely, it's something like the following. For `[(a, b), (b, c), (c, d)]`, we first resolve `a` and `d` during graph construction (root demes shall default to `a=inf`; leaf demes shall default to `d=0`; demes with one ancestor shall have `a=ancestor_end_time`, with the constraint that `a!=0`; in all other cases `a` and `d` must be supplied by the user). Finally, each of `b` and `c` must be supplied by the user at least once.

**Comment by grahamgower** [comment]
> leaf demes shall default to `d=0`

I'm not sure this is correct. I think right now we have all demes defaulting to `deme.end_time=0`. Does this seem appropriate?

**Comment by jeromekelleher** [comment]
That sounds about right @grahamgower. 

What would you think about making (say) ``start_time`` and attribute of Deme and ``end_time`` and attribute of Epoch? So, then there would only be one way of specifying a time for an Epoch, and describing/implementing these rules would be much easier (the alternative might be more appropriate, e.e., making ``end_time`` and attribute of Deme, I haven't thought it through).

I'm worried that it's quite easy to mix-up start_time and end_time when you're writing Epoch descriptions, and it could be a source of subtle bugs, as well being a bit of a mess for parser writers.

**Comment by grahamgower** [comment]
I don't quite follow. Surely the epoch would still need `start_time` and `end_time` attributes. We actually still have both `deme.start_time` and `deme.end_time` attributes, but a couple of weeks ago we decided these were redundant with the epoch attributes (and @apragsdale has an open PR to remove the deme attributes, among other things: https://github.com/popsim-consortium/demes-python/pull/172).

**Comment by grahamgower** [comment]
Oh, now I see what you mean! I'm not sure if we want that though... let me think about it a while...

**Comment by jeromekelleher** [comment]
So to be concrete, I'm suggesting:
```yaml
defaults: 
    epoch: {initial_size: 1}
demes:
  start_time: a
  epochs: 
   - {end_time: b}
   - {end_time: c}
   - {end_time: d}
```

I don't know if it's a good idea, but it'd be good to explore.

**Comment by jeromekelleher** [comment]
@apragsdale @moldpopgen, any thoughts here? I'm worried that by having both a start_time and and end_time on each of the n epochs, we're then specifying 2n bits of information when we only need n + 1. This leads to a perl-like situation in which there's lots of different ways of specifying the same set of time intervals, when really there should only be one. (This is a good principle from the Zen of Python, I think).

My suggestion is that we resolve this by giving Epoch (say) just a ``start_time`` so we can uniquely specify the n time points, and then given Deme an ``end_time``, which specifies the final, bracketing time point (if needed). We could equally do it the other way around like my suggestion above.

**Comment by molpopgen** [comment]
So, the concrete proposal seems sensible, and matches up with how some of the [exiting examples](https://github.com/popsim-consortium/demes-python/blob/main/examples/gutenkunst_ooa.yml) are written.  For the Gutenkunst model, only the end times are specified.

**Comment by apragsdale** [comment]
Sorry for slow replies this week..

Currently, I've got an open PR that made the specification very flexible, where either start or end times can be specified and the function just figures it out how to fill it all in or raise an error for inconsistencies. I'm not a huge fan of what I did there, for the reasons you've mentioned, and I think your example of setting start time for a deme (unless it's inherited from its ancestor, or omitted to default to inf with no ancestors), and epochs just have end time. That means that epoch start times internally inherit from the previous epoch's end time. I think this is the right way to go, where more recent demes and epochs inherit start times from their predecessors.

**Comment by grahamgower** [comment]
I still have reservations, but there's certainly multiple appealing reasons to go with this. So lets do it.

**Comment by apragsdale** [comment]
@grahamgower would you rather specify that first epoch's start time within the epoch level, instead of the deme level?

**Comment by grahamgower** [comment]
Well, yes. But doesn't that defeat the goal of only being able to specifying one time per epoch "boundary", as the start_time could then be given for any epoch?

**Comment by jeromekelleher** [comment]
OK, great, looks like we're converging. The main question is: should an Epoch have a ``start_time`` or an ``end_time``? Everything else follows from this.

**Comment by molpopgen** [comment]
I think that I prefer end times.  I'm trying to work out (in my head) if one of the other is more/less natural for "ghost" demes that don't make it all the way to the present day sampling time?

**Comment by andrewkern** [comment]
just read through this issue-- another vote for explicitly specifying `end_time`.

**Comment by grahamgower** [comment]
Sounds like we're going with `end_time`!

**Comment by grahamgower** [comment]
> Would we require that the last epoch has an `end_time`, or allow something like the final epoch's `end_time` defaults to zero if not give. Meaning, is this a valid demes description for a single deme that exists for all time with size 100?
> 
> ```yaml
> demes:
> - id: a
>   epochs: 
>   - initial_size: 100
> ```

Yeah, I think we still want this. It's a very neat simplification which will be very common in real-world demographic models.

**Comment by jeromekelleher** [comment]
Ok, looks like that's a decision then. I'll implement this in the reference implementation and report by ack.
