### ISSUE TITLE
HDM: Selfing and cloning rate should default to zero

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#33]
Currently no definition of what the default for ``cloning_rate`` and ``selfing_rate`` is. In the interest of being explicit about what values we expect in a fully resolved model, we should give these a default of 0.

Can't see a good reason to give them a non-zero default, and leaving a "null" value in the resolved output just pushes the decision onto the simulator, leading to ambiguity.

We should also give clear language on what a simulator should do in the case of seeing a non-zero value for these parameters if it doesn't support the feature (I guess this is a more general point too - programs should explicitly check for parts of the model they don't support and raise an error).

**Comment by jeromekelleher** [comment]
I think we can set the default values to 0 in the HDM schema  - @grahamgower, any objections?

**Comment by grahamgower** [comment]
That sounds like the right thing to do.

**Comment by apragsdale** [comment]
I'm not sure about setting default `selfing_rate` to zero. In a diploid WF model (and what the coalescent approximates), the chance of choosing both parents to be the same individual is 1/N, not 0. Instead, it might be better to leave the default as `None` or `null` and specify that it refers to this case?

**Comment by jeromekelleher** [comment]
Good point @apragsdale. Hmm.

**Comment by MattHartfield** [comment]
Hey all, just saw this. The SLiM manual also contains a statement about this issue, and how there's residual selfing even in fully outcrossing simulations when their selfing rate is set to zero (see their section 6.3.1). A good solution would be to also clarify this point in accompanying documentation.

**Comment by jeromekelleher** [comment]
That's a good idea @MattHartfield, I like it.

**Comment by grahamgower** [comment]
This needs some prose in the HDM.

**Comment by grahamgower** [comment]
This was completed in #139.
