### ISSUE TITLE
HDM: Definition of default semantics for size_function

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#34]
The parser should output fully a resolved model, with non-null values for every field that effects the model. Thus, we need to specify the semantics of what the default values should be. We could do something like:

> The value of an Epoch's ``size_function`` should be resolved after the epoch's start_size and end_size values have been resolved. If the ``start_size`` and ``end_size`` are equal, the size function should be resolved to ``"constant"``, or otherwise to ``exponential``.

However, I think it's simpler if we just default to ``exponential``, and leave it up to the implementation to realise that the growth rate is 0. They will need to do this anyway, unless we make it part of the spec that parsers should raise an error if the size function is exponential and the start and end sizes are the same. This seems like it would end up being fragile and annoying to me, though.

**Comment by jeromekelleher** [comment]
Actually, come to think of it, what's the point of the ``"constant"`` size function then? It doesn't really serve any purpose, since you can always specify that the start and end sizes are the same.

This would simplify our lives a bit, since we could say that the only currently supported value is ``exponential`` and anything else is an error. We also then don't have to check if the ``size_function`` is constant but with different start and end sizes.

**Comment by grahamgower** [comment]
I think there was some discussion about "linear" being a reasonable size_function. It seems strange to me that we would have this keyword, yet allow only "exponential". Having the keyword at all indicates we think it will be useful, but then allowing only one value prevents the keyword from being used.
