### ISSUE TITLE
If time_units is "generations" should we allow ``generation_time`` to be set?

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#41]
The value won't be used, so maybe it should be an error to specify it? On the other hand, it could be useful information that might have been used in inference or something?

The reference parser currently throws an error.

**Comment by apragsdale** [comment]
I think it should be allowed, for the reason you mentioned. Although if we allow that, you could reasonably ask why we don't have a mutation rate or recombination map (doi?) fields as well, as those could also have been parameters used to infer the model.

**Comment by jeromekelleher** [comment]
OK, let's allow it then. It's a grey area and I doubt it'll end up leading to significant misunderstandings in the future.

To avoid feature creep, I think we should keep Demes about parameters that aren't about the genome - so, we don't ever talk about mutation rate, etc. See #44.
