### ISSUE TITLE
Should ``Graph.description`` really be mandatory?

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#42]
Currently the spec says that the top-level description field in the graph is mandatory. I see the logic for this: we want to try to encourage people to describe their graphs. I wonder if it's a bit heavy-handed though.

Thoughts @apragsdale @molpopgen?

If we keep it as mandatory, is the empty string valid input?

**Comment by molpopgen** [comment]
I'm okay with it being optional (None or string).  For graphs describing
models from inferences (Gutenkunst OOA and the like), having the
description makes sense.  But if one is generating models as a simulation
exercise, it could get annoying.

**Comment by jeromekelleher** [comment]
> But if one is generating models as a simulation exercise, it could get annoying.

That's what I was thinking.

**Comment by apragsdale** [comment]
I agree - we hadn't thought of that case of generating many models at first, but having to include a description for each would be silly.
