### ISSUE TITLE
Move detailed descriptions out of JSON schema

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#46]
It's a good idea to put the full description of the spec into the JSON schema yaml file, but I think it has some limitations. It makes it more difficult to cross reference sections, and the formatting we can do is pretty limited. Also, (and the clincher for me) it results in pretty much unreadable error messages coming out of ``jsonschema.validate()``, which writes out the full schema text and you therefore get pages of text you need to scroll through.

So, I suggest we structure the schema description as an RST file, and put in terse descriptions with URL section links to the full documentation in the schema text. It should be easy enough to make stable URLs for these, now?

**Comment by grahamgower** [comment]
Yeah, that sounds like a good plan.

**Comment by jeromekelleher** [comment]
I'm going to make a pass at this now @grahamgower, in case you were planning on doing stuff in here.

**Comment by grahamgower** [comment]
Thanks Jerome, I've been putting this off. :)

**Comment by jeromekelleher** [comment]
Closed in #80
