### ISSUE TITLE
Change Deme.id to Deme.name

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#59]
I think we should change the current ``id`` attribute on Deme to ``name``. There's two main reasons for this:

1. Using ``id`` is intrusive for downstream implementations as they will already have some concept of a population/deme ID, and it's unlikely to match up with what we're requiring here. For example, msprime/tskit have zero-indexed integers as population IDs, and SLiM has one-indexed integers as population IDs. Neither can map the concept of "Deme id" directly into their data models, requiring icky workarounds where we add a "name" which corresponds to the Demes ID. This is both messy and will confuse users.
2. It's not as descriptive. "ID" has connotations of some unique, opaque identifier for a thing. We don't want people to give demes IDs, we want people to **name** then, in meaningful, memorable ways. Calling it a ``name`` gets this idea across much better.

Thoughts/objections?

**Comment by grahamgower** [comment]
Unfortunately, I think you're right. `name` would fit in better in a lot of ways.

**Comment by grahamgower** [comment]
This seemingly simple change will likely need lots of changes for related variable names and docs.

**Comment by jeromekelleher** [comment]
Yes, sorry. This will only get worse over time though - who wants to rip off the bandaid? I'll do the spec repo if you do ``demes-python``?

**Comment by grahamgower** [comment]
> Yes, sorry. This will only get worse over time though - who wants to rip off the bandaid? I'll do the spec repo if you do `demes-python`?

Deal!

**Comment by jeromekelleher** [comment]
OK - @molpopgen, @apragsdale any objections?

**Comment by molpopgen** [comment]
Makes sense to me.

**Comment by apragsdale** [comment]
No objections here.

**Comment by jeromekelleher** [comment]
OK, I'll sort this out here when I get a chance.
