### ISSUE TITLE
JSON doesn't support Infinity

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-spec#70]
Apparently the JSON spec explicitly does not permit `Infinity`, which we require to represent start times. The Python json implementation can deal with the special value `Infinity`, and converts to/from float infinity just fine. However, it seems this isn't a widespread extension. Not sure what to do about this, because it means we can't really serialize to json (at least, we can't expect this to be more portable than yaml).

https://stackoverflow.com/questions/1423081/json-left-out-infinity-and-nan-json-status-in-ecmascript
https://stackoverflow.com/questions/61841001/handling-infinity-values-in-json

**Comment by jeromekelleher** [comment]
That's unfortunate. Any suggestions?

**Comment by grahamgower** [comment]
I've been filtering the json output through a regex to replace `\<Infinity\>` with the string-valued `"Infinity"`. The string value is converted to a float/double `inf` in by both `atof()` and `strtod()` in C. Perhaps more importantly, the string is also transparently converted to a float `inf` in both SLiM (`asFloat("Infinity")`) and R (`as.numeric("Infinity")`).

https://github.com/grahamgower/demes-slim/blob/main/examples/convert.sh

**Comment by grahamgower** [comment]
Javascript's `parseFloat("Infinity")` also converts to a Javascript `Infinity`. So it's about as JSONy as we're likely to get.

**Comment by jeromekelleher** [comment]
SGTM. I guess we need to document this in the spec?

**Comment by grahamgower** [comment]
See also #98, and final decision https://github.com/popsim-consortium/demes-spec/pull/98#issuecomment-872430331
