### ISSUE TITLE
Validate examples using JSON schema

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#79]
As noted in [this comment](https://github.com/popsim-consortium/demes-paper/pull/20#discussion_r655141925) the JSON schema doesn't currently validate examples in which we have "Infinity" values.

We should close this loophole, and add a CI step where we validate all the examples against the schema.

**Comment by grahamgower** [comment]
Hopefully this isn't too awkward. I'm slightly worried that we're using YAML for the json schema, which does use `.inf`.
