### ISSUE TITLE
Docs build broken by recent updates 

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#81]
Looks like I broke a bunch of stuff with the latest change @grahamgower - I assume this is to do with the new version of JupyterBook? We're seeing a lot of stuff like {{ example.replace(“LABEL”, “01”) }} in the final docs.

**Comment by grahamgower** [comment]
It looks like the `substitution` myst extension needs to be added back in.
https://jupyterbook.org/customize/config.html#configuration-defaults
