### ISSUE TITLE
Force resolved migrations to be asymmetric

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#84]
From @grahamgower in #83 
 
>  If there are three or more demes, it may not be possible to resolve the start/end times of a symmetric migration without breaking it down into pairwise migrations. Obviously, these pairwise migrations could be symmetric, but maybe we should force them to be asymmetric for a resolved model?

Pros:
- The fully resolved schema is simpler and probably easier to define

Cons:
- Loss of information from the original model when communicated to the simulator. The simulator would like to know if this was a Symmetric migration, or at least it would be a more faithful representation of the original model
- Current parsers will need to be updated (I'd imagine)

**Comment by grahamgower** [comment]
All parsers (include the ref impl) are resolving to pairs of some asymmetric migration data structure. The implementation and user APIs are both simpler and user-level code needs fewer code paths.

**Comment by jeromekelleher** [comment]
OK, sounds good. @molpopgen, @apragsdale ?

**Comment by molpopgen** [comment]
I don't foresee any issues here--@apragsdale?

**Comment by apragsdale** [comment]
Sounds good to me.

**Comment by jeromekelleher** [comment]
OK, looks like we can update the fully-resolved schema to reflect this then.

**Comment by grahamgower** [comment]
I added #111 and #112 to track this separately in the MDM and HDM.
