### ISSUE TITLE
Need better names for data models

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#86]
It's becoming clear to me that we need more precise names for the two different data models. Referring to various different things as "Demes" is getting very confusing. I suggest we come up with some acronyms for the fully resolved and (simplified? redundant?) data models. How about "Demes Machine Data Model (Demes MDM)", and "Demes Human Data Model (Demes HDM)", and then we can refer to these as the MDM and HDM through the spec and paper?

Very much open to better ideas here!

**Comment by jeromekelleher** [comment]
So, the HDM is a superset of the MDM which allows for certain fields to be omitted and provides a mechanism for specifying defaults to avoid repetition of values.

**Comment by grahamgower** [comment]
See #16.

**Comment by jeromekelleher** [comment]
So what do we think of the Demes HDM and MDM? @molpopgen, @apragsdale

**Comment by jeromekelleher** [comment]
I don't find the terms we bandied about in #16 all that helpful - the term "Graph" isn't very descriptive (I don't really care if it's a graph, what's it *for*), and saying things are "resolved" or "minimal" or whatever again don't get me much closer to what the things are for. I'm struggling to find a way of laying out the information in the spec in a rigorous and understandable way, so the choice of terminology is crucial here.

**Comment by apragsdale** [comment]
I think this makes sense to be more descriptive in our terminology - human/machine data model, or human/machine readable model?, though maybe compact/redundant similarly describes that? I'm not too picky, and happy to go with what you think is the most natural description.

**Comment by grahamgower** [comment]
> I don't find the terms we bandied about in #16 all that helpful - the term "Graph" isn't very descriptive (I don't really care if it's a graph or a tree or whatever, what's it _for_), and saying things are "resolved" or "minimal" or whatever again don't get me much closer to what the things are for.

I don't think HDM and MDM do the job here either. You still have to define what they mean somewhere. \*shrug\*

**Comment by jeromekelleher** [comment]
Well of course we have to define what they mean - it's about referring to the different things withing the context of a large and complex document. Saying "reduced graph" a hundred times doesn't appeal

**Comment by jeromekelleher** [comment]
Closing this as we've settled on MDM and HDM in the spec for now. Can open a new issue if we want to change them.
