### ISSUE TITLE
Why allow "null" for description rather than the empty string?

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#94]
The [MDM](https://popsim-consortium.github.io/demes-spec-docs/main/specification.html#schema) has almost no null values allowed, with the ``description`` fields being one of the exceptions. What's the semantic difference between having a ``null`` value as opposed to the empty string? Aren't we making implementations lives more complex by forcing them to support both, which are, essentially, the same thing?

If we allow for both, then we need to explain the difference and give guidance on what to do in either case.

**Comment by grahamgower** [comment]
An empty string here makes sense to me. This will need some changes in demes-python to allow/emit an empty string, but they should be straightforward.
