### ISSUE TITLE
MDM schema should be a subschema of HDM

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-spec#97]
I'm sure we can check that this is true and add a test for that. A quick search brought up https://github.com/haggholm/is-json-schema-subset

**Comment by grahamgower** [comment]
Instead of trying to use the javascript package above (I'm not cool enough to know how to use a javascript package), we could generate data that is valid under the MDM schema using https://github.com/Zac-HD/hypothesis-jsonschema and validate that against the HDM schema.

**Comment by jeromekelleher** [comment]
I think we're doing that as one of the permutations [here](https://github.com/popsim-consortium/demes-spec/blob/main/reference_implementation/tests.py#L1094) - we validate all the outputs of the parser against the MDM schema. Not bullet proof, but a reasonable check?

**Comment by grahamgower** [comment]
Yeah, that's pretty good. It does depend on the reference implementation though. It is possible, although unlikely, that a bug could somehow mask a subschema property issue. Also, if you're considering a change to either/both of the schemas then the reference implementation must be changed first in order to check the schemas are consistent.
